
# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: orderer.example.org

    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: solo

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: Org1
    Domain: org1.example.org

    # ---------------------------------------------------------------------------
    # "CA"
    # ---------------------------------------------------------------------------
    CA:
       Hostname: ca # implicitly ca.org1.example.org

    # ---------------------------------------------------------------------------
    # "Template"
    # ---------------------------------------------------------------------------
    Template:
      Count: 3

    # ---------------------------------------------------------------------------
    # "Users"
    # ---------------------------------------------------------------------------
    # Count: The number of user accounts _in addition_ to Admin
    # ---------------------------------------------------------------------------
    Users:
      Count: 0
  # ---------------------------------------------------------------------------
  # Org2
  # ---------------------------------------------------------------------------
  - Name: Org2
    Domain: org2.example.org

    # ---------------------------------------------------------------------------
    # "CA"
    # ---------------------------------------------------------------------------
    CA:
       Hostname: ca # implicitly ca.org2.example.org

    # ---------------------------------------------------------------------------
    # "Template"
    # ---------------------------------------------------------------------------
    Template:
      Count: 3

    # ---------------------------------------------------------------------------
    # "Users"
    # ---------------------------------------------------------------------------
    # Count: The number of user accounts _in addition_ to Admin
    # ---------------------------------------------------------------------------
    Users:
      Count: 0
